sonar.projectKey=artech-base-project
sonar.projectName=Artech Base Project
sonar.projectVersion=1.0

# Path direktori yang ingin dianalisis
sonar.sources=.

# Path untuk mengecualikan folder vendor/test jika ada
# sonar.exclusions=**/*_test.go,**/vendor/**
